
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ru: {
    title: "Оформление документов – быстрее чем ты думаешь",
    subtitle: "Финансовое обеспечение для твоего авто быстро и удобно",
    heroBtn2: "Чат-бот 🤖 консультация",
    ownerBtn: "👤 Оформить для владельца",
    ownerSub: "Для тех, кто является собственником ТС",
    driverBtn: "🚗 Оформить для водителя по доверенности",
    driverSub: "Для водителей с правом управления по доверенности",
    fullName: "ФИО",
    passportNum: "Номер паспорта",
    address: "Адрес",
    phone: "Номер телефона",
    carDataSpec: "Марка, модель, год машины",
    bishkekCode: "Бишкек-41715006",
    photoBtn: "Фото документов",
    payBtn: "Оплатить",
    receiverFullName: "ФИО получателя",
    receiverPassport: "Номер паспорта получателя",
    receiverAddress: "Адрес получателя",
    receiverPhone: "Номер телефона получателя",
    driverFullName: "ФИО водителя",
    driverPassport: "Номер паспорта водителя",
    driverAddress: "Адрес водителя",
    driverPhone: "Номер телефона водителя",
    featuresTitle: "Наши преимущества",
    feat1: "Многоязычная поддержка",
    feat1Sub: "Общаемся на вашем языке",
    feat2: "Быстрое оформление",
    feat2Sub: "Документы за 15 минут",
    feat4: "Поддержка 24/7",
    feat4Sub: "Мы всегда на связи",
    contactUs: "Связаться",
    chatPlaceholder: "Введите ваше сообщение...",
    initialBotMessage: "Здравствуйте! Я ассистент ERLAN AUTO. Как я могу помочь вам с оформлением документов сегодня?",
    georgia: "Грузия",
    kyrgyzstan: "Кыргызстан",
    officeTitle: "Наш офис в Рустави",
    officeAddress: "Авторынок AUTOPAPA, рядом с заправкой Wisey и Karting (Кыргызская Юрта), г. Рустави, Грузия",
    routeBtn: "Маршрут",
    callBtn: "Позвонить",
    footerAbout: "Ваш надежный партнер в международной логистике.",
    footerServicesTitle: "Услуги",
    footerService1: "Подбор авто",
    footerService2: "Помощь в оформлении документов",
    footerService3: "Логистика из Грузии",
    footerService4: "Консультации 24/7",
    footerContactsTitle: "Контакты",
    footerBishkek: "Рустави, Грузия",
    footerRights: "Все права защищены",
    onlineStatus: "В сети",
    // Fix: Missing properties used in MainForm.tsx
    mainFormTitle: "Оформление заявки",
    clientType: "Тип клиента",
    clientIndividual: "Физ. лицо",
    clientCompany: "Юр. лицо",
    carData: "Данные авто",
    origin: "Откуда",
    destination: "Куда",
    submitBtn: "Отправить"
  },
  kg: {
    title: "Документтерди каттоо – сиз ойлогондон тезирээк",
    subtitle: "Унааңыз үчүн каржылык камсыздоо тез жана ыңгайлуу",
    heroBtn2: "Чат-бот 🤖 консультация",
    ownerBtn: "👤 Унаа ээсине каттоо",
    ownerSub: "Унаанын ээси болгондор үчүн",
    driverBtn: "🚗 Ишеним кат боюнча айдоочуга каттоо",
    driverSub: "Ишеним кат боюнча башкарган айдоочулар үчүн",
    fullName: "Аты-жөнү",
    passportNum: "Паспорттун номери",
    address: "Дареги",
    phone: "Телефон номери",
    carDataSpec: "Унаанын маркасы, модели, жылы",
    bishkekCode: "Бишкек-41715006",
    photoBtn: "Документтердин сүрөтү",
    payBtn: "Төлөө",
    receiverFullName: "Алуучунун аты-жөнү",
    receiverPassport: "Алуучунун паспортунун номери",
    receiverAddress: "Алуучунун дареги",
    receiverPhone: "Алуучунун телефон номери",
    driverFullName: "Айдоочунун аты-жөнү",
    driverPassport: "Айдоочунун паспортунун номери",
    driverAddress: "Айдоочунун дареги",
    driverPhone: "Айдоочунун телефон номери",
    featuresTitle: "Биздин артыкчылыктар",
    feat1: "Көп тилдүү тейлөө",
    feat1Sub: "Өз тилиңизде баарлашыңыз",
    feat2: "Тез каттоо",
    feat2Sub: "15 мүнөттө документтер",
    feat4: "24/7 колдоо",
    feat4Sub: "Биз дайыма байланыштабыз",
    contactUs: "Байланыш",
    chatPlaceholder: "Билдирүүңүздү киргизиңиз...",
    initialBotMessage: "Саламатсызбы! Мен ERLAN AUTO ассистентимин. Бүгүн сизге документтерди каттоо боюнча кантип жардам бере алам?",
    georgia: "Грузия",
    kyrgyzstan: "Кыргызстан",
    officeTitle: "Биздин Руставидеги кеңсебиз",
    officeAddress: "AUTOPAPA автобазары, Wisey май куюучу жайынын жана Karting жанында (Кыргыз боз үйү), Рустави ш., Грузия",
    routeBtn: "Багыт",
    callBtn: "Чалуу",
    footerAbout: "Эл аралык логистикадагы сиздин ишенимдүү өнөктөшүңүз.",
    footerServicesTitle: "Кызматтар",
    footerService1: "Унаа тандоо",
    footerService2: "Документтерди каттоодо жардам",
    footerService3: "Грузиядан логистика",
    footerService4: "24/7 кеңеш берүү",
    footerContactsTitle: "Байланыштар",
    footerBishkek: "Рустави, Грузия",
    footerRights: "Бардык укуктар корголгон",
    onlineStatus: "Онлайн",
    // Fix: Missing properties used in MainForm.tsx
    mainFormTitle: "Өтүнмөнү толтуруу",
    clientType: "Кардардын түрү",
    clientIndividual: "Жеке жак",
    clientCompany: "Юридикалык жак",
    carData: "Унаа маалыматы",
    origin: "Кайдан",
    destination: "Кайда",
    submitBtn: "Жөнөтүү"
  },
  en: {
    title: "Documentation - Faster than you think",
    subtitle: "Financial security for your car quickly and conveniently",
    heroBtn2: "Chat-bot 🤖 consultation",
    ownerBtn: "👤 Apply for Owner",
    ownerSub: "For vehicle owners",
    driverBtn: "🚗 Apply for Driver by Proxy",
    driverSub: "For drivers with power of attorney",
    fullName: "Full Name",
    passportNum: "Passport Number",
    address: "Address",
    phone: "Phone Number",
    carDataSpec: "Make, Model, Year of the car",
    bishkekCode: "Bishkek-41715006",
    photoBtn: "Photo of Documents",
    payBtn: "Pay",
    receiverFullName: "Receiver Full Name",
    receiverPassport: "Receiver Passport Number",
    receiverAddress: "Receiver Address",
    receiverPhone: "Receiver Phone Number",
    driverFullName: "Driver Full Name",
    driverPassport: "Driver Passport Number",
    driverAddress: "Driver Address",
    driverPhone: "Driver Phone Number",
    featuresTitle: "Our Advantages",
    feat1: "Multilingual Support",
    feat1Sub: "We speak your language",
    feat2: "Fast Processing",
    feat2Sub: "Documents in 15 minutes",
    feat4: "24/7 Support",
    feat4Sub: "Always here to help",
    contactUs: "Contact Us",
    chatPlaceholder: "Type your message...",
    initialBotMessage: "Hello! I am the ERLAN AUTO assistant. How can I help you today?",
    georgia: "Georgia",
    kyrgyzstan: "Kyrgyzstan",
    officeTitle: "Our Office in Rustavi",
    officeAddress: "AUTOPAPA Car Market, near Wisey Gas Station and Karting (Kyrgyz Yurt), Rustavi, Georgia",
    routeBtn: "Route",
    callBtn: "Call",
    footerAbout: "Your reliable partner in international logistics.",
    footerServicesTitle: "Services",
    footerService1: "Car Selection",
    footerService2: "Documentation Assistance",
    footerService3: "Logistics from Georgia",
    footerService4: "24/7 Consultations",
    footerContactsTitle: "Contacts",
    footerBishkek: "Rustavi, Georgia",
    footerRights: "All rights reserved",
    onlineStatus: "Online",
    // Fix: Missing properties used in MainForm.tsx
    mainFormTitle: "Application Form",
    clientType: "Client Type",
    clientIndividual: "Individual",
    clientCompany: "Company",
    carData: "Car Data",
    origin: "Origin",
    destination: "Destination",
    submitBtn: "Submit"
  },
  ge: {
    title: "დოკუმენტაციის გაფორმება – იმაზე სწრაფად, ვიდრე ფიქრობთ",
    subtitle: "ფინანსური უზრუნველყოფა თქვენი ავტომობილისთვის სწრაფად და მოხერხებულად",
    heroBtn2: "ჩატ-ბოტის 🤖 კონსულტაცია",
    ownerBtn: "👤 მფლობელისთვის გაფორმება",
    ownerSub: "მფლობელებისთვის",
    driverBtn: "🚗 მძღოლისთვის გაფორმება მინდობილობით",
    driverSub: "მძღოლებისთვის მინდობილობის საფუძველზე",
    fullName: "სახელი და გვარი",
    passportNum: "პასპორტის ნომერი",
    address: "მისამართი",
    phone: "ტელეფონის ნომერი",
    carDataSpec: "ავტომობილის მარკა, მოდელი, წელი",
    bishkekCode: "ბიშკეკი-41715006",
    photoBtn: "დოკუმენტების ფოტო",
    payBtn: "გადახდა",
    receiverFullName: "მიმღების სახელი და გვარი",
    receiverPassport: "მიმღების პასპორტის ნომერი",
    receiverAddress: "მიმღების მისამართი",
    receiverPhone: "მიმღების ტელეფონის ნომერი",
    driverFullName: "მძღოლის სახელი და გვარი",
    driverPassport: "მძღოლის პასპორტის ნომერი",
    driverAddress: "მძღოლის მისამართი",
    driverPhone: "მძღოლის ტელეფონის ნომერი",
    featuresTitle: "ჩვენი უპირატესობები",
    feat1: "მრავალენოვანი მხარდაჭერა",
    feat1Sub: "ვსაუბრობთ თქვენს ენაზე",
    feat2: "სწრაფი გაფორმება",
    feat2Sub: "დოკუმენტები 15 წუთში",
    feat4: "24/7 მხარდაჭერა",
    feat4Sub: "ყოველთვის ხაზზე ვართ",
    contactUs: "კონტაქტი",
    chatPlaceholder: "შეიყვანეთ შეტყობინება...",
    initialBotMessage: "გამარჯობა! მე ვარ ERLAN AUTO-ს ასისტენტი. რით შემიძლია დაგეხმაროთ?",
    georgia: "საქართველო",
    kyrgyzstan: "ყირგიზეთი",
    officeTitle: "ჩვენი ოფისი რუსთავში",
    officeAddress: "ავტობაზრობა AUTOPAPA, Wisey-ს ბენზინგასამართ სადგურთან და Karting-თან ახლოს (ყირგიზული იურტა), რუსთავი, საქართველო",
    routeBtn: "მარშრუტი",
    callBtn: "დარეკვა",
    footerAbout: "თქვენი საიმედო პარტნიორი საერთაშორისო ლოჯისტიკაში.",
    footerServicesTitle: "სერვისები",
    footerService1: "ავტომობილის შერჩევა",
    footerService2: "დახმარება დოკუმენტაციის გაფორმებაში",
    footerService3: "ლოჯისტიკა საქართველოდან",
    footerService4: "კონსულტაციები 24/7",
    footerContactsTitle: "კონტაქტები",
    footerBishkek: "რუსთავი, საქართველო",
    footerRights: "ყველა უფლება დაცულია",
    onlineStatus: "ონლაინ",
    // Fix: Missing properties used in MainForm.tsx
    mainFormTitle: "განაცხადის ფორმა",
    clientType: "კლიენტის ტიპი",
    clientIndividual: "ფიზიკური პირი",
    clientCompany: "იურიდიული პირი",
    carData: "ავტომობილის მონაცემები",
    origin: "საიდან",
    destination: "სად",
    submitBtn: "გაგზავნა"
  },
  kz: {
    title: "Құжаттарды рәсімдеу – сіз ойлағаннан да жылдам",
    subtitle: "Автокөлігіңіз үчүн қаржылық қамтасыз ету жылдам әрі ыңғайлы",
    heroBtn2: "Чат-бот 🤖 кеңес беру",
    ownerBtn: "👤 Иесі үчүн рәсімдеу",
    ownerSub: "Көлік иелері үчүн",
    driverBtn: "🚗 Сенімхат бойынша жүргізуші үчүн рәсімдеу",
    driverSub: "Сенімхат бойынша басқаратын жүргізушілер үчүн",
    fullName: "Аты-жөнү",
    passportNum: "Төлқұжат нөмірі",
    address: "Мекен-жайы",
    phone: "Телефон нөмірі",
    carDataSpec: "Көліктің маркасы, моделі, жылы",
    bishkekCode: "Бишкек-41715006",
    photoBtn: "Құжаттардың суреті",
    payBtn: "Төлеу",
    receiverFullName: "Алушының аты-жөнү",
    receiverPassport: "Алушының төлқұжат нөмірі",
    receiverAddress: "Алушының мекен-жайы",
    receiverPhone: "Алушының телефон нөмірі",
    driverFullName: "Жүргізушіның аты-жөнү",
    driverPassport: "Жүргізушіның төлқұжат нөмірі",
    driverAddress: "Жүргізушіның мекен-жайы",
    driverPhone: "Жүргізушіның телефон нөмірі",
    featuresTitle: "Біздің артықшылықтар",
    feat1: "Көптілді қолдау",
    feat1Sub: "Сіздің тіліңізде сөйлейміз",
    feat2: "Жылдам рәсімдеу",
    feat2Sub: "15 минутта құжаттар",
    feat4: "24/7 қолдау",
    feat4Sub: "Біз әрқашан байланыстамыз",
    contactUs: "Байланысу",
    chatPlaceholder: "Хабарламаңызды енгізіңіз...",
    initialBotMessage: "Сәлеметсіз бе! Мен ERLAN AUTO ассистентімін. Қалай көмектесе алам?",
    georgia: "Грузия",
    kyrgyzstan: "Қырғызстан",
    officeTitle: "Біздің Руставидегі кеңсебиз",
    officeAddress: "AUTOPAPA автобазары, Wisey заправкасының жана Karting жанында (Қырғыз киіз үйі), Рустави қ., Грузия",
    routeBtn: "Маршрут",
    callBtn: "Қоңырау шалу",
    footerAbout: "Халықаралық логистикадағы сіздин сенімді серіктесіңіз.",
    footerServicesTitle: "Қызметтер",
    footerService1: "Автокөлік таңдау",
    footerService2: "Құжаттарды рәсімдеуге көмек",
    footerService3: "Грузиядан логистика",
    footerService4: "24/7 кеңес беру",
    footerContactsTitle: "Байланыштар",
    footerBishkek: "Рустави, Грузия",
    footerRights: "Барлық құқықтар қорғалған",
    onlineStatus: "Желіде",
    // Fix: Missing properties used in MainForm.tsx
    mainFormTitle: "Өтінімді толтыру",
    clientType: "Клиент түрі",
    clientIndividual: "Жеке тұлға",
    clientCompany: "Заңды тұлға",
    carData: "Автокөлік деректері",
    origin: "Қайдан",
    destination: "Қайда",
    submitBtn: "Жіберу"
  }
};

export const LANGUAGES = [
  { code: 'ru', label: 'Русский', country: 'ru' },
  { code: 'kg', label: 'Кыргызча', country: 'kg' },
  { code: 'en', label: 'English', country: 'gb' },
  { code: 'ge', label: 'Georgian', country: 'ge' },
  { code: 'kz', label: 'Қазақша', country: 'kz' }
];
